### ISSUE TITLE
[GitHub Request] Add necessary credentials for GitHub App Token to Remote Metadata Client repo

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/.github#255]
### What is the type of request?

Secret Update

### Details of the request

Please add appropriate conditions to run the `backport` workflow: https://github.com/opensearch-project/opensearch-remote-metadata-sdk/blob/main/.github/workflows/backport.yml

### Additional information to support your request

I believe these are `APP_ID` and `APP_PRIVATE_KEY` associated with this step.
```yaml
      - name: GitHub App token
        id: github_app_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: 22958780
```

### When does this request need to be completed?

7-10 business days is acceptable but the earlier the better.

### Notes

Track the progress of your request here: https://github.com/orgs/opensearch-project/projects/208/views/33.
Member of @opensearch-project/admin will take a look at the request soon.
Thanks!
